"""first commit

Revision ID: 6507323c1dab
Revises: 
Create Date: 2023-12-29 11:36:00.438994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6507323c1dab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Categories_ibfk_1', 'Categories', type_='foreignkey')
    op.drop_column('Categories', 'created_by_employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Categories', sa.Column('created_by_employee_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True))
    op.create_foreign_key('Categories_ibfk_1', 'Categories', 'Employees', ['created_by_employee_id'], ['id'])
    # ### end Alembic commands ###
