"""first commit

Revision ID: 76e5cc26309f
Revises: 
Create Date: 2023-12-01 16:08:34.808091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '76e5cc26309f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('products',
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('promotion_price', sa.DECIMAL(precision=18, scale=0), nullable=True),
    sa.Column('category_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('manufacture_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_name')
    )
    op.create_table('images',
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('product_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_classifications',
    sa.Column('item_classification_name', sa.String(length=255), nullable=True),
    sa.Column('product_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_classification_name')
    )
    op.create_table('sub_item_classifications',
    sa.Column('sub_item_classification_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=18, scale=0), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('item_classification_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_classification_id'], ['item_classifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub_item_classification_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_item_classifications')
    op.drop_table('item_classifications')
    op.drop_table('images')
    op.drop_table('products')
    op.drop_table('categories')
    # ### end Alembic commands ###
