# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/admin/home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(1470, 914)
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#tableWidget QHeaderView, #tableWidget {\n"
"    border: 0px;\n"
"     background-color: #fff;\n"
"    border-radius: 5px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"#tableWidget QHeaderView::section {\n"
"    font-family: \"Time New Roman\", \"Time\", \"serif\";\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    text-align: left;\n"
"    border-radius: 14px;\n"
"    border-bottom: 1px solid #353535;\n"
"    border-top: 1px solid #353535;\n"
"    padding-left:     10px;\n"
"}\n"
"\n"
"#stackedWidget{\n"
"    background: #fff;\n"
"}\n"
"\n"
"#userDialogForm QLabel{\n"
"    color: #000;\n"
"    font-size: 16px;\n"
"    font-weight: 400;\n"
"}\n"
"\n"
"#userDialogForm  QLineEdit{\n"
"    border: 1px solid #e0e5e9;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    line-height: 1.2;\n"
"    min-height:34px;\n"
"    height: 34px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: 1px solid #e0e5e9;\n"
"    font-size: 16px;\n"
"    line-height: 1.2;\n"
"    min-height:34px;\n"
"    height: 34px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"#centralwidget QLineEdit:focus {\n"
"    border-color: #5500ff;\n"
"}\n"
"\n"
"#btnCancelUser{\n"
"    background: #ebebeb;\n"
"    outline: none;\n"
"    border: 1px solid #e0e0e0;\n"
"    min-height: 36px;\n"
"    min-width: 80px;\n"
"    border-radius: 4px;\n"
"    padding: 2px 12px;\n"
"    overflow: hidden;\n"
"}\n"
"\n"
"#btnCancelUser:hover{\n"
"    background: #f4f5f8;\n"
"}\n"
"\n"
"#btnUser{\n"
"    min-height: 36px;\n"
"    border-radius: 4px;\n"
"    overflow: hidden;\n"
"    color: #fff;\n"
"    background: #2979ff;\n"
"    border: 1px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    min-height: 36px;\n"
"    font-size: 14px;\n"
"    padding: 2px 12px;\n"
"}\n"
"\n"
"#btnUser:hover{\n"
"        background: #0062cc;\n"
"}\n"
"\n"
"#footerUserContainer{\n"
"     background-color: #fbfbfe;\n"
"    padding: 12px 24px;\n"
"    border-top: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"#backBtn{\n"
"    margin-left: 10px;\n"
"    margin-right: 10px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"#dialogTitle{\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#popupHeader{\n"
"    height: 60px;\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"#widget_12, #widget_11, #widget_10, #widget_7{\n"
"        border-bottom: 1px solid #e0e0e0;\n"
"}    \n"
"\n"
"#userDialogForm{\n"
"        border-radius: 4px;\n"
"        border: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"\n"
"\n"
"#userDialogFormSubContainer{\n"
"    background: #e9e9e9;\n"
"    border-radius: 4px;\n"
"}\n"
" #formInput_4 QLabel {\n"
"    margin-top: 10px;\n"
"}\n"
"QHBoxLayout QLabel{\n"
"    background: red;\n"
"}\n"
"\n"
"#labelName, #labelUserName, #labelPassword, #labelConfirm{\n"
"    margin-top:30px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    min-width: 80px;\n"
"    min-height: 36px;\n"
"    border-radius: 4px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#error_name, #error_password, #error_username, #error_confirm{\n"
"    padding-top: 8px;\n"
"    padding-bottom: 8px;\n"
"}\n"
"\n"
"#addUserBtn{\n"
"        width:  100px;\n"
"        background: #2979ff;\n"
"        color: #fff;\n"
"}\n"
"\n"
"#addUserBtn:hover{\n"
"    background: #1a73e8;\n"
"}\n"
"\n"
"#addUserBtn QLabel{\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"#search_btn_2{\n"
"    min-weight: 40px;\n"
"    max-weight: 40px;\n"
"    border: none;\n"
"}\n"
"\n"
"#searchBoxContainer QLineEdit, #searchBoxContainer_2 QLineEdit{\n"
"    border: none;\n"
"}\n"
"\n"
"#searchBoxContainer{\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 3.5px;    \n"
"    min-height: 36px;\n"
"}\n"
"\n"
"#searchBoxContainer_2{\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 3.5px;\n"
"    min-height: 36px;\n"
"}\n"
"\n"
"#headerAdmin{\n"
"    background: #fff;\n"
"}\n"
"\n"
"#change_btn{\n"
"    max-width: 20px !important;\n"
"}\n"
"\n"
"#change_btn:hover{\n"
"    background: #ddd;\n"
"}\n"
"\n"
"#change_btn, #search_btn_5,  #search_btn_2, #backBtn{\n"
"    min-width: 30px;\n"
"}\n"
"\n"
"#search_input_5{\n"
"    padding: 0;\n"
"    padding-left: 10px\n"
"}\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.headerAdmin = QtWidgets.QWidget(self.widget_3)
        self.headerAdmin.setMinimumSize(QtCore.QSize(0, 0))
        self.headerAdmin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.headerAdmin.setObjectName("headerAdmin")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.headerAdmin)
        self.horizontalLayout_4.setContentsMargins(0, 10, 0, 10)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.change_btn = QtWidgets.QPushButton(self.headerAdmin)
        self.change_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.change_btn.sizePolicy().hasHeightForWidth())
        self.change_btn.setSizePolicy(sizePolicy)
        self.change_btn.setMinimumSize(QtCore.QSize(54, 40))
        self.change_btn.setMaximumSize(QtCore.QSize(44, 16777215))
        self.change_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.change_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/resources/icon/menu-4-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_btn.setIcon(icon)
        self.change_btn.setIconSize(QtCore.QSize(14, 14))
        self.change_btn.setCheckable(True)
        self.change_btn.setObjectName("change_btn")
        self.horizontalLayout_4.addWidget(self.change_btn, 0, QtCore.Qt.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(236, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.searchBoxContainer_2 = QtWidgets.QWidget(self.headerAdmin)
        self.searchBoxContainer_2.setMinimumSize(QtCore.QSize(0, 38))
        self.searchBoxContainer_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.searchBoxContainer_2.setObjectName("searchBoxContainer_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.searchBoxContainer_2)
        self.horizontalLayout.setContentsMargins(0, 1, 0, 1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchBox_4 = QtWidgets.QHBoxLayout()
        self.searchBox_4.setContentsMargins(2, 0, -1, 0)
        self.searchBox_4.setSpacing(0)
        self.searchBox_4.setObjectName("searchBox_4")
        self.search_input_5 = QtWidgets.QLineEdit(self.searchBoxContainer_2)
        self.search_input_5.setMinimumSize(QtCore.QSize(210, 34))
        self.search_input_5.setInputMask("")
        self.search_input_5.setObjectName("search_input_5")
        self.searchBox_4.addWidget(self.search_input_5)
        self.search_btn_5 = QtWidgets.QPushButton(self.searchBoxContainer_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_btn_5.sizePolicy().hasHeightForWidth())
        self.search_btn_5.setSizePolicy(sizePolicy)
        self.search_btn_5.setMinimumSize(QtCore.QSize(54, 40))
        self.search_btn_5.setMaximumSize(QtCore.QSize(40, 16777215))
        self.search_btn_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_btn_5.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/resources/icon/search-13-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_btn_5.setIcon(icon1)
        self.search_btn_5.setObjectName("search_btn_5")
        self.searchBox_4.addWidget(self.search_btn_5)
        self.horizontalLayout.addLayout(self.searchBox_4)
        self.horizontalLayout_4.addWidget(self.searchBoxContainer_2)
        spacerItem1 = QtWidgets.QSpacerItem(236, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.user_btn = QtWidgets.QPushButton(self.headerAdmin)
        self.user_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/user-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.user_btn.setIcon(icon2)
        self.user_btn.setObjectName("user_btn")
        self.horizontalLayout_4.addWidget(self.user_btn)
        self.verticalLayout_5.addWidget(self.headerAdmin)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_8 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_9 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_6)
        self.userPage = QtWidgets.QWidget()
        self.userPage.setObjectName("userPage")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.userPage)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.userContainer = QtWidgets.QWidget(self.userPage)
        self.userContainer.setObjectName("userContainer")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.userContainer)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.titleContainer = QtWidgets.QWidget(self.userContainer)
        self.titleContainer.setMinimumSize(QtCore.QSize(0, 0))
        self.titleContainer.setObjectName("titleContainer")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.titleContainer)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.widget_4 = QtWidgets.QWidget(self.titleContainer)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.gridLayout_12.addWidget(self.widget_4, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.titleContainer)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.searchBoxContainer = QtWidgets.QWidget(self.widget_2)
        self.searchBoxContainer.setObjectName("searchBoxContainer")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.searchBoxContainer)
        self.horizontalLayout_5.setContentsMargins(0, 1, 0, 1)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.searchBox = QtWidgets.QHBoxLayout()
        self.searchBox.setContentsMargins(2, -1, -1, -1)
        self.searchBox.setSpacing(0)
        self.searchBox.setObjectName("searchBox")
        self.search_input_2 = QtWidgets.QLineEdit(self.searchBoxContainer)
        self.search_input_2.setMinimumSize(QtCore.QSize(220, 44))
        self.search_input_2.setObjectName("search_input_2")
        self.searchBox.addWidget(self.search_input_2)
        self.search_btn_2 = QtWidgets.QPushButton(self.searchBoxContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_btn_2.sizePolicy().hasHeightForWidth())
        self.search_btn_2.setSizePolicy(sizePolicy)
        self.search_btn_2.setMinimumSize(QtCore.QSize(54, 40))
        self.search_btn_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.search_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_btn_2.setText("")
        self.search_btn_2.setIcon(icon1)
        self.search_btn_2.setObjectName("search_btn_2")
        self.searchBox.addWidget(self.search_btn_2)
        self.horizontalLayout_5.addLayout(self.searchBox)
        self.horizontalLayout_6.addWidget(self.searchBoxContainer)
        spacerItem2 = QtWidgets.QSpacerItem(308, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setMinimumSize(QtCore.QSize(100, 0))
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.addUserBtn = QtWidgets.QPushButton(self.widget_5)
        self.addUserBtn.setMinimumSize(QtCore.QSize(124, 40))
        self.addUserBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/resources/icon/plus-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addUserBtn.setIcon(icon3)
        self.addUserBtn.setAutoRepeatInterval(100)
        self.addUserBtn.setObjectName("addUserBtn")
        self.verticalLayout_12.addWidget(self.addUserBtn)
        self.horizontalLayout_6.addWidget(self.widget_5)
        self.gridLayout_12.addWidget(self.widget_2, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.titleContainer, 0, 0, 1, 1)
        self.tableContainer = QtWidgets.QWidget(self.userContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableContainer.sizePolicy().hasHeightForWidth())
        self.tableContainer.setSizePolicy(sizePolicy)
        self.tableContainer.setObjectName("tableContainer")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tableContainer)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.frame = QtWidgets.QFrame(self.tableContainer)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setRowCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.gridLayout_9.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.tableContainer, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.userContainer, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.userPage)
        self.modelUser = QtWidgets.QWidget()
        self.modelUser.setObjectName("modelUser")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.modelUser)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_6 = QtWidgets.QWidget(self.modelUser)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.popupHeader = QtWidgets.QWidget(self.widget_6)
        self.popupHeader.setMinimumSize(QtCore.QSize(0, 60))
        self.popupHeader.setObjectName("popupHeader")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.popupHeader)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.backBtn = QtWidgets.QPushButton(self.popupHeader)
        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/resources/icon/back.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backBtn.setIcon(icon4)
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout_7.addWidget(self.backBtn)
        self.dialogTitle = QtWidgets.QLabel(self.popupHeader)
        self.dialogTitle.setObjectName("dialogTitle")
        self.horizontalLayout_7.addWidget(self.dialogTitle)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.verticalLayout_7.addWidget(self.popupHeader)
        self.widget_9 = QtWidgets.QWidget(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, -1, 30)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.userDialogForm = QtWidgets.QWidget(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userDialogForm.sizePolicy().hasHeightForWidth())
        self.userDialogForm.setSizePolicy(sizePolicy)
        self.userDialogForm.setMinimumSize(QtCore.QSize(900, 300))
        self.userDialogForm.setObjectName("userDialogForm")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.userDialogForm)
        self.verticalLayout_10.setContentsMargins(50, 20, 50, 30)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.userDialogFormContainer_2 = QtWidgets.QVBoxLayout()
        self.userDialogFormContainer_2.setContentsMargins(0, 0, 0, 0)
        self.userDialogFormContainer_2.setSpacing(0)
        self.userDialogFormContainer_2.setObjectName("userDialogFormContainer_2")
        self.widget_7 = QtWidgets.QWidget(self.userDialogForm)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_14 = QtWidgets.QWidget(self.widget_7)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.formInput_5 = QtWidgets.QHBoxLayout()
        self.formInput_5.setContentsMargins(-1, 0, -1, -1)
        self.formInput_5.setSpacing(0)
        self.formInput_5.setObjectName("formInput_5")
        self.labelName = QtWidgets.QLabel(self.widget_14)
        self.labelName.setMinimumSize(QtCore.QSize(200, 0))
        self.labelName.setObjectName("labelName")
        self.formInput_5.addWidget(self.labelName, 0, QtCore.Qt.AlignTop)
        self.widget_15 = QtWidgets.QWidget(self.widget_14)
        self.widget_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_16.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.name_le = QtWidgets.QLineEdit(self.widget_15)
        self.name_le.setMinimumSize(QtCore.QSize(222, 46))
        self.name_le.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.name_le.setText("")
        self.name_le.setPlaceholderText("Họ và tên")
        self.name_le.setClearButtonEnabled(True)
        self.name_le.setObjectName("name_le")
        self.verticalLayout_16.addWidget(self.name_le)
        self.error_name = QtWidgets.QLabel(self.widget_15)
        self.error_name.setText("")
        self.error_name.setObjectName("error_name")
        self.verticalLayout_16.addWidget(self.error_name)
        self.formInput_5.addWidget(self.widget_15, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_20.addLayout(self.formInput_5)
        self.horizontalLayout_9.addWidget(self.widget_14)
        self.userDialogFormContainer_2.addWidget(self.widget_7)
        self.widget_10 = QtWidgets.QWidget(self.userDialogForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.labelUserName = QtWidgets.QLabel(self.widget_10)
        self.labelUserName.setMinimumSize(QtCore.QSize(200, 0))
        self.labelUserName.setObjectName("labelUserName")
        self.horizontalLayout_13.addWidget(self.labelUserName, 0, QtCore.Qt.AlignTop)
        self.formInput_6 = QtWidgets.QWidget(self.widget_10)
        self.formInput_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.formInput_6.setObjectName("formInput_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.formInput_6)
        self.verticalLayout_13.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.username_le = QtWidgets.QLineEdit(self.formInput_6)
        self.username_le.setMinimumSize(QtCore.QSize(222, 46))
        self.username_le.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.username_le.setClearButtonEnabled(True)
        self.username_le.setObjectName("username_le")
        self.verticalLayout_13.addWidget(self.username_le)
        self.error_username = QtWidgets.QLabel(self.formInput_6)
        self.error_username.setText("")
        self.error_username.setObjectName("error_username")
        self.verticalLayout_13.addWidget(self.error_username, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_13.addWidget(self.formInput_6, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.userDialogFormContainer_2.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.userDialogForm)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.labelPassword = QtWidgets.QLabel(self.widget_11)
        self.labelPassword.setMinimumSize(QtCore.QSize(200, 0))
        self.labelPassword.setObjectName("labelPassword")
        self.horizontalLayout_15.addWidget(self.labelPassword, 0, QtCore.Qt.AlignTop)
        self.formInput_7 = QtWidgets.QWidget(self.widget_11)
        self.formInput_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.formInput_7.setObjectName("formInput_7")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.formInput_7)
        self.verticalLayout_14.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.password_le = QtWidgets.QLineEdit(self.formInput_7)
        self.password_le.setMinimumSize(QtCore.QSize(222, 46))
        self.password_le.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.password_le.setText("")
        self.password_le.setPlaceholderText("Mật khẩu")
        self.password_le.setClearButtonEnabled(True)
        self.password_le.setObjectName("password_le")
        self.verticalLayout_14.addWidget(self.password_le)
        self.error_password = QtWidgets.QLabel(self.formInput_7)
        self.error_password.setText("")
        self.error_password.setObjectName("error_password")
        self.verticalLayout_14.addWidget(self.error_password, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_15.addWidget(self.formInput_7, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        self.userDialogFormContainer_2.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.userDialogForm)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.labelConfirm = QtWidgets.QLabel(self.widget_12)
        self.labelConfirm.setMinimumSize(QtCore.QSize(200, 0))
        self.labelConfirm.setObjectName("labelConfirm")
        self.horizontalLayout_17.addWidget(self.labelConfirm, 0, QtCore.Qt.AlignTop)
        self.formInput_3 = QtWidgets.QWidget(self.widget_12)
        self.formInput_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.formInput_3.setObjectName("formInput_3")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.formInput_3)
        self.verticalLayout_15.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.confirm_le = QtWidgets.QLineEdit(self.formInput_3)
        self.confirm_le.setMinimumSize(QtCore.QSize(222, 46))
        self.confirm_le.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.confirm_le.setText("")
        self.confirm_le.setClearButtonEnabled(True)
        self.confirm_le.setObjectName("confirm_le")
        self.verticalLayout_15.addWidget(self.confirm_le)
        self.error_confirm = QtWidgets.QLabel(self.formInput_3)
        self.error_confirm.setText("")
        self.error_confirm.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.error_confirm.setObjectName("error_confirm")
        self.verticalLayout_15.addWidget(self.error_confirm, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_17.addWidget(self.formInput_3, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_17)
        self.userDialogFormContainer_2.addWidget(self.widget_12)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.userDialogFormContainer_2.addItem(spacerItem5)
        self.userDialogFormSubContainer = QtWidgets.QWidget(self.userDialogForm)
        self.userDialogFormSubContainer.setObjectName("userDialogFormSubContainer")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.userDialogFormSubContainer)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, 10, 20, 10)
        self.horizontalLayout_19.setSpacing(10)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem6)
        self.btnCancelUser = QtWidgets.QPushButton(self.userDialogFormSubContainer)
        self.btnCancelUser.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCancelUser.setObjectName("btnCancelUser")
        self.horizontalLayout_19.addWidget(self.btnCancelUser)
        self.btnUser = QtWidgets.QPushButton(self.userDialogFormSubContainer)
        self.btnUser.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnUser.setObjectName("btnUser")
        self.horizontalLayout_19.addWidget(self.btnUser)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        self.userDialogFormContainer_2.addWidget(self.userDialogFormSubContainer)
        self.verticalLayout_10.addLayout(self.userDialogFormContainer_2)
        self.horizontalLayout_11.addWidget(self.userDialogForm)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        self.verticalLayout_7.addWidget(self.widget_9)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addWidget(self.widget_6)
        self.stackedWidget.addWidget(self.modelUser)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_3, 0, 2, 1, 1)
        self.icon_only_widget = QtWidgets.QWidget(self.centralwidget)
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logo_label_1 = QtWidgets.QLabel(self.icon_only_widget)
        self.logo_label_1.setMinimumSize(QtCore.QSize(50, 50))
        self.logo_label_1.setMaximumSize(QtCore.QSize(50, 50))
        self.logo_label_1.setText("")
        self.logo_label_1.setPixmap(QtGui.QPixmap(":/icon/icon/Logo.png"))
        self.logo_label_1.setScaledContents(True)
        self.logo_label_1.setObjectName("logo_label_1")
        self.horizontalLayout_3.addWidget(self.logo_label_1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.home_btn_1.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon/home-4-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon/home-4-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.home_btn_1.setIcon(icon5)
        self.home_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.home_btn_1.setCheckable(True)
        self.home_btn_1.setAutoExclusive(True)
        self.home_btn_1.setObjectName("home_btn_1")
        self.verticalLayout.addWidget(self.home_btn_1)
        self.dashborad_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.dashborad_btn_1.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icon/dashboard-5-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/icon/icon/dashboard-5-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.dashborad_btn_1.setIcon(icon6)
        self.dashborad_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.dashborad_btn_1.setCheckable(True)
        self.dashborad_btn_1.setAutoExclusive(True)
        self.dashborad_btn_1.setObjectName("dashborad_btn_1")
        self.verticalLayout.addWidget(self.dashborad_btn_1)
        self.orders_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.orders_btn_1.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icon/activity-feed-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/icon/icon/activity-feed-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.orders_btn_1.setIcon(icon7)
        self.orders_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.orders_btn_1.setCheckable(True)
        self.orders_btn_1.setAutoExclusive(True)
        self.orders_btn_1.setObjectName("orders_btn_1")
        self.verticalLayout.addWidget(self.orders_btn_1)
        self.products_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.products_btn_1.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/icon/product-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/icon/icon/product-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.products_btn_1.setIcon(icon8)
        self.products_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.products_btn_1.setCheckable(True)
        self.products_btn_1.setAutoExclusive(True)
        self.products_btn_1.setObjectName("products_btn_1")
        self.verticalLayout.addWidget(self.products_btn_1)
        self.customers_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.customers_btn_1.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/icon/group-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/icon/icon/group-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.customers_btn_1.setIcon(icon9)
        self.customers_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.customers_btn_1.setCheckable(True)
        self.customers_btn_1.setAutoExclusive(True)
        self.customers_btn_1.setObjectName("customers_btn_1")
        self.verticalLayout.addWidget(self.customers_btn_1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem8 = QtWidgets.QSpacerItem(20, 375, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.exit_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.exit_btn_1.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/icon/close-window-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn_1.setIcon(icon10)
        self.exit_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.exit_btn_1.setObjectName("exit_btn_1")
        self.verticalLayout_3.addWidget(self.exit_btn_1)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        self.full_menu_widget = QtWidgets.QWidget(self.centralwidget)
        self.full_menu_widget.setMinimumSize(QtCore.QSize(256, 0))
        self.full_menu_widget.setObjectName("full_menu_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.full_menu_widget)
        self.verticalLayout_4.setContentsMargins(0, 10, -1, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logo_label_2 = QtWidgets.QLabel(self.full_menu_widget)
        self.logo_label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.logo_label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.logo_label_2.setText("")
        self.logo_label_2.setPixmap(QtGui.QPixmap(":/icon/icon/Logo.png"))
        self.logo_label_2.setScaledContents(True)
        self.logo_label_2.setObjectName("logo_label_2")
        self.horizontalLayout_2.addWidget(self.logo_label_2)
        self.logo_label_3 = QtWidgets.QLabel(self.full_menu_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.logo_label_3.setFont(font)
        self.logo_label_3.setObjectName("logo_label_3")
        self.horizontalLayout_2.addWidget(self.logo_label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.home_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.home_btn_2.setMinimumSize(QtCore.QSize(104, 40))
        self.home_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_btn_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.home_btn_2.setIcon(icon5)
        self.home_btn_2.setIconSize(QtCore.QSize(14, 14))
        self.home_btn_2.setCheckable(True)
        self.home_btn_2.setAutoExclusive(True)
        self.home_btn_2.setObjectName("home_btn_2")
        self.verticalLayout_2.addWidget(self.home_btn_2, 0, QtCore.Qt.AlignLeft)
        self.dashborad_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.dashborad_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dashborad_btn_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dashborad_btn_2.setIcon(icon6)
        self.dashborad_btn_2.setIconSize(QtCore.QSize(14, 14))
        self.dashborad_btn_2.setCheckable(True)
        self.dashborad_btn_2.setAutoExclusive(True)
        self.dashborad_btn_2.setObjectName("dashborad_btn_2")
        self.verticalLayout_2.addWidget(self.dashborad_btn_2, 0, QtCore.Qt.AlignLeft)
        self.orders_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.orders_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.orders_btn_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.orders_btn_2.setIcon(icon7)
        self.orders_btn_2.setIconSize(QtCore.QSize(14, 14))
        self.orders_btn_2.setCheckable(True)
        self.orders_btn_2.setAutoExclusive(True)
        self.orders_btn_2.setObjectName("orders_btn_2")
        self.verticalLayout_2.addWidget(self.orders_btn_2, 0, QtCore.Qt.AlignLeft)
        self.products_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.products_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.products_btn_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.products_btn_2.setIcon(icon8)
        self.products_btn_2.setIconSize(QtCore.QSize(14, 14))
        self.products_btn_2.setCheckable(True)
        self.products_btn_2.setAutoExclusive(True)
        self.products_btn_2.setObjectName("products_btn_2")
        self.verticalLayout_2.addWidget(self.products_btn_2, 0, QtCore.Qt.AlignLeft)
        self.customers_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.customers_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.customers_btn_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.customers_btn_2.setIcon(icon9)
        self.customers_btn_2.setIconSize(QtCore.QSize(14, 14))
        self.customers_btn_2.setCheckable(True)
        self.customers_btn_2.setAutoExclusive(True)
        self.customers_btn_2.setObjectName("customers_btn_2")
        self.verticalLayout_2.addWidget(self.customers_btn_2, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 373, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.exit_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.exit_btn_2.setIcon(icon10)
        self.exit_btn_2.setIconSize(QtCore.QSize(14, 14))
        self.exit_btn_2.setObjectName("exit_btn_2")
        self.verticalLayout_4.addWidget(self.exit_btn_2)
        self.gridLayout.addWidget(self.full_menu_widget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1470, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(5)
        self.exit_btn_1.clicked.connect(MainWindow.close)
        self.change_btn.toggled['bool'].connect(self.icon_only_widget.setVisible)
        self.dashborad_btn_1.toggled['bool'].connect(self.dashborad_btn_2.setChecked)
        self.exit_btn_2.clicked.connect(MainWindow.close)
        self.products_btn_2.toggled['bool'].connect(self.products_btn_1.setChecked)
        self.products_btn_1.toggled['bool'].connect(self.products_btn_2.setChecked)
        self.customers_btn_2.toggled['bool'].connect(self.customers_btn_1.setChecked)
        self.home_btn_1.toggled['bool'].connect(self.home_btn_2.setChecked)
        self.home_btn_2.toggled['bool'].connect(self.home_btn_1.setChecked)
        self.orders_btn_2.toggled['bool'].connect(self.orders_btn_1.setChecked)
        self.customers_btn_1.toggled['bool'].connect(self.customers_btn_2.setChecked)
        self.change_btn.toggled['bool'].connect(self.full_menu_widget.setHidden)
        self.dashborad_btn_2.toggled['bool'].connect(self.dashborad_btn_1.setChecked)
        self.orders_btn_1.toggled['bool'].connect(self.orders_btn_2.setChecked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_input_5.setPlaceholderText(_translate("MainWindow", "Search..."))
        self.label_4.setText(_translate("MainWindow", "Home Page"))
        self.label_5.setText(_translate("MainWindow", "Dashboard Page"))
        self.label_6.setText(_translate("MainWindow", "Orders Page"))
        self.label_7.setText(_translate("MainWindow", "Product Page"))
        self.label_8.setText(_translate("MainWindow", "Customers Page"))
        self.label_9.setText(_translate("MainWindow", "Search Page"))
        self.label.setText(_translate("MainWindow", "Danh sách người dùng"))
        self.search_input_2.setPlaceholderText(_translate("MainWindow", "Search..."))
        self.addUserBtn.setText(_translate("MainWindow", "Thêm mới"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "#"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Website"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Password"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Operation"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "2"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.dialogTitle.setText(_translate("MainWindow", "Thêm mới tài khoản"))
        self.labelName.setText(_translate("MainWindow", "Họ và tên:"))
        self.labelUserName.setText(_translate("MainWindow", "Tài khoản:"))
        self.username_le.setPlaceholderText(_translate("MainWindow", "Email hoặc số điện thoại"))
        self.labelPassword.setText(_translate("MainWindow", "Mật khẩu:"))
        self.labelConfirm.setText(_translate("MainWindow", "Nhập lại mật khẩu"))
        self.confirm_le.setPlaceholderText(_translate("MainWindow", "Nhập lại mật khẩu"))
        self.btnCancelUser.setText(_translate("MainWindow", "Hủy"))
        self.btnUser.setText(_translate("MainWindow", "Lưu"))
        self.logo_label_3.setText(_translate("MainWindow", "Sidebar"))
        self.home_btn_2.setText(_translate("MainWindow", "Trang chủ"))
        self.dashborad_btn_2.setText(_translate("MainWindow", "Tổng quan"))
        self.orders_btn_2.setText(_translate("MainWindow", "Quản lý đơn hàng"))
        self.products_btn_2.setText(_translate("MainWindow", "Quản lý sản phẩm"))
        self.customers_btn_2.setText(_translate("MainWindow", "Quản lý tài khoản"))
        self.exit_btn_2.setText(_translate("MainWindow", "Exit"))
import ui.resource_rc
